# Generated by Django 5.0.6 on 2024-07-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_remove_equipo_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='equipment',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
