# Generated by Django 5.0.6 on 2024-07-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_equipo_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='equipment',
            new_name='equipo',
        ),
    ]
